//  JAB-036: buf.c — the port of jab/buf.cpp; a near-pure embedded-JS bundle,
//  carried over verbatim (C has no raw string literal, so it is escaped).
#include "JABC.h"

//  The Buf cursor class + the buffer constructors and the public fd<->buffer
//  helpers live in JS (the binding holds no memory): a Buf wraps a JS-owned
//  Uint8Array plus the PAST|DATA|IDLE boundaries, and its methods call the
//  native leaves (io._read/_write/_mmap/_ram, utf8.encodeInto) which only touch
//  the backing bytes.
static const char *JABC_BUF_JS =
    "\n"
    "(function (g) {\n"
    "  \"use strict\";\n"
    "  const U8 = Uint8Array;\n"
    "\n"
    "  //  Buf: a Uint8Array (the bytes, JS-owned) plus a cursor.\n"
    "  //    PAST [0,_data)   already consumed (take/skip/write)\n"
    "  //    DATA [_data,_idle) the live payload\n"
    "  //    IDLE [_idle,cap)   free space (feed/read flow here)\n"
    "  class Buf {\n"
    "    constructor(bytes, data, idle) {\n"
    "      this.bytes = bytes;\n"
    "      this._data = data | 0;\n"
    "      this._idle = (idle === undefined ? data : idle) | 0;\n"
    "      this.cap = bytes.length;\n"
    "    }\n"
    "    static over(u8) { return new Buf(u8, 0, u8.length); } // bytes are DATA (read)\n"
    "    static into(u8) { return new Buf(u8, 0, 0); }         // bytes are IDLE (fill)\n"
    "\n"
    "    get size() { return this._idle - this._data; }   // live byte count\n"
    "    get room() { return this.cap - this._idle; }      // free byte count\n"
    "    get empty() { return this._idle === this._data; }\n"
    "\n"
    "    data() { return this.bytes.subarray(this._data, this._idle); } // no-copy view\n"
    "    idle() { return this.bytes.subarray(this._idle, this.cap); }\n"
    "    past() { return this.bytes.subarray(0, this._data); }\n"
    "\n"
    "    feed(src) {                                       // append (u8bFeed)\n"
    "      const s = (src instanceof Buf) ? src.data() : src;\n"
    "      if (s.length > this.room) throw \"NOROOM\";\n"
    "      this.bytes.set(s, this._idle);\n"
    "      this._idle += s.length;\n"
    "      return s.length;\n"
    "    }\n"
    "    feed1(b) {                                        // append one byte\n"
    "      if (this.room < 1) throw \"NOROOM\";\n"
    "      this.bytes[this._idle++] = b & 0xff;\n"
    "      return 1;\n"
    "    }\n"
    "    feedStr(str) {                                    // utf8-encode into IDLE\n"
    "      const n = g.utf8.encodeInto(str, this.idle());\n"
    "      this._idle += n;\n"
    "      return n;\n"
    "    }\n"
    "    fed(n) {                                          // commit a manual idle write\n"
    "      if (n < 0 || n > this.room) throw \"BADARG\";\n"
    "      this._idle += n;\n"
    "      return this;\n"
    "    }\n"
    "\n"
    "    take(n) {                                         // consume from DATA front (u8bUsed)\n"
    "      if (n < 0 || n > this.size) throw \"BADARG\";\n"
    "      const v = this.bytes.subarray(this._data, this._data + n);\n"
    "      this._data += n;\n"
    "      return v;\n"
    "    }\n"
    "    skip(n) {\n"
    "      if (n < 0 || n > this.size) throw \"BADARG\";\n"
    "      this._data += n;\n"
    "      return this;\n"
    "    }\n"
    "\n"
    "    shed(n) {                                         // un-append (u8bShed)\n"
    "      if (n < 0 || n > this.size) throw \"BADARG\";\n"
    "      this._idle -= n;\n"
    "      return this;\n"
    "    }\n"
    "    pop() {\n"
    "      if (this.empty) throw \"NODATA\";\n"
    "      return this.bytes[--this._idle];\n"
    "    }\n"
    "    reset() { this._data = 0; this._idle = 0; return this; }\n"
    "    shift() {                                         // compact, drop PAST (u8bShift)\n"
    "      if (this._data === 0) return this;\n"
    "      this.bytes.copyWithin(0, this._data, this._idle);\n"
    "      this._idle -= this._data;\n"
    "      this._data = 0;\n"
    "      return this;\n"
    "    }\n"
    "    splice(off, cut, paste) {                         // in-place edit within DATA\n"
    "      const p = (paste instanceof Buf) ? paste.data() : (paste || new U8(0));\n"
    "      if (off < 0 || cut < 0 || off + cut > this.size) throw \"BADARG\";\n"
    "      const delta = p.length - cut;\n"
    "      if (delta > this.room) throw \"NOROOM\";\n"
    "      const d = this._data;\n"
    "      this.bytes.copyWithin(d + off + p.length, d + off + cut, this._idle);\n"
    "      this.bytes.set(p, d + off);\n"
    "      this._idle += delta;\n"
    "      return this;\n"
    "    }\n"
    "\n"
    "    grow(n) {                                         // enlarge capacity\n"
    "      if (n <= this.cap) return this;\n"
    "      if (this._grow) { this._grow(n); return this; } // mapped-backing hook\n"
    "      const nb = new U8(n);\n"
    "      nb.set(this.bytes.subarray(0, this._idle));\n"
    "      this.bytes = nb;\n"
    "      this.cap = n;\n"
    "      return this;\n"
    "    }\n"
    "    msync() { g.io._msync(this.bytes); return this; } // flush a mapped backing\n"
    "  }\n"
    "\n"
    "  g.Buf = Buf;\n"
    "  const io = g.io, utf8 = g.utf8;\n"
    "  io.Buf = Buf;\n"
    "\n"
    "  //  Constructors\n"
    "  io.buf = (n) => Buf.into(new U8(n));               // engine ArrayBuffer\n"
    "  io.ram = (n) => Buf.into(io._ram(n));              // anonymous mmap\n"
    "  io.mmap = (path, mode, size) => {                  // file mapping\n"
    "    mode = mode || \"r\";\n"
    "    const u = io._mmap(path, mode, size || 0);\n"
    "    return (mode === \"c\") ? Buf.into(u) : Buf.over(u);\n"
    "  };\n"
    "  io.book = () => {\n"
    "    throw \"io.book(): booked mmap not wired yet (use io.mmap + io.resize)\";\n"
    "  };\n"
    "\n"
    "  //  text sugar over the native leaf\n"
    "  utf8.Encode = (s) => {\n"
    "    const b = new U8(s.length * 3 + 4);              // 3 bytes/UTF-16 unit upper bound\n"
    "    return b.subarray(0, utf8.encodeInto(s, b));\n"
    "  };\n"
    "\n"
    "  //  fd <-> buffer.  A Buf advances its own cursor; a bare Uint8Array is\n"
    "  //  single-shot (no cursor to advance).\n"
    "  io.read = (fd, b) => {\n"
    "    if (b instanceof Buf) { const n = io._read(fd, b.idle()); b._idle += n; return n; }\n"
    "    return io._read(fd, b);\n"
    "  };\n"
    "  io.write = (fd, b) => {\n"
    "    if (b instanceof Buf) { const n = io._write(fd, b.data()); b._data += n; return n; }\n"
    "    return io._write(fd, b);\n"
    "  };\n"
    "  io.readAll = (fd, b) => {\n"
    "    if (b instanceof Buf) { let t = 0, n; while (b.room > 0 && (n = io.read(fd, b)) > 0) t += n; return t; }\n"
    "    let v = b, t = 0, n; while (v.length && (n = io._read(fd, v)) > 0) { t += n; v = v.subarray(n); } return t;\n"
    "  };\n"
    "  io.writeAll = (fd, b) => {\n"
    "    if (b instanceof Buf) { let t = 0, n; while (b.size > 0) { n = io.write(fd, b); if (n <= 0) break; t += n; } return t; }\n"
    "    let v = b, t = 0, n; while (v.length) { n = io._write(fd, v); if (n <= 0) break; t += n; v = v.subarray(n); } return t;\n"
    "  };\n"
    "  //  v1: readv/writev are loops, not a single readv(2)/writev(2) syscall.\n"
    "  io.readv = (fd, list) => { let t = 0; for (const b of list) t += io.read(fd, b); return t; };\n"
    "  io.writev = (fd, list) => { let t = 0; for (const b of list) t += io.writeAll(fd, b); return t; };\n"
    "\n"
    "  io.stdin = 0; io.stdout = 1; io.stderr = 2;\n"
    "})(this);\n"
    "\n";

ok64 JABCInstallBuf(JSContext *ctx, JSValueConst global) {
    (void)ctx;
    (void)global;
    JABCExecute(JABC_BUF_JS);
    return OK;
}
