//  JAB-036: jab/console.cpp — JAB-002's pure-JS `console`, ported verbatim.
//  It layers over utf8.Encode + io.writeAll; no native leaf of its own.
#include "JABC.h"

static const char *JABC_CONSOLE_JS =
    "(function (g) {\n"
    "  \"use strict\";\n"
    "  const io = g.io, utf8 = g.utf8;\n"
    "\n"
    "  //  A small util.inspect: scalars stringified, objects/arrays rendered\n"
    "  //  JSON-ish (single-quoted strings, bareword keys), cycles → [Circular].\n"
    "  function inspect(v, seen) {\n"
    "    const t = typeof v;\n"
    "    if (t === \"string\") return \"'\" + v.replace(/\\\\/g, \"\\\\\\\\\")\n"
    "        .replace(/'/g, \"\\\\'\").replace(/\\n/g, \"\\\\n\") + \"'\";\n"
    "    if (t === \"bigint\") return String(v) + \"n\";\n"
    "    if (t === \"function\") return \"[Function\" + (v.name ? \": \" + v.name : \" (anonymous)\") + \"]\";\n"
    "    if (t === \"symbol\") return v.toString();\n"
    "    if (t !== \"object\" || v === null) return String(v);  // number/boolean/undefined/null\n"
    "    seen = seen || [];\n"
    "    if (seen.indexOf(v) >= 0) return \"[Circular]\";\n"
    "    if (v instanceof Error) return v.stack || (v.name + \": \" + v.message);\n"
    "    seen.push(v);\n"
    "    let out;\n"
    "    if (Array.isArray(v)) {\n"
    "      out = v.length ? \"[ \" + v.map((x) => inspect(x, seen)).join(\", \") + \" ]\" : \"[]\";\n"
    "    } else {\n"
    "      const keys = Object.keys(v);\n"
    "      const body = keys.map((k) => {\n"
    "        const key = /^[A-Za-z_$][\\w$]*$/.test(k) ? k : \"'\" + k + \"'\";\n"
    "        return key + \": \" + inspect(v[k], seen);\n"
    "      });\n"
    "      out = body.length ? \"{ \" + body.join(\", \") + \" }\" : \"{}\";\n"
    "    }\n"
    "    seen.pop();\n"
    "    return out;\n"
    "  }\n"
    "\n"
    "  //  Stringify one non-specifier arg: a top-level string prints raw (no\n"
    "  //  quotes), everything else goes through inspect.\n"
    "  function str(a) { return typeof a === \"string\" ? a : inspect(a); }\n"
    "\n"
    "  //  Node-style util.format over an arguments/array `a`.\n"
    "  function format(a) {\n"
    "    if (a.length === 0) return \"\";\n"
    "    let i = 1, out;\n"
    "    const first = a[0];\n"
    "    if (typeof first === \"string\" && /%[sdifjoOc%]/.test(first)) {\n"
    "      out = first.replace(/%([sdifjoOc%])/g, (m, k) => {\n"
    "        if (k === \"%\") return \"%\";\n"
    "        if (i >= a.length) return m;          // not enough args: leave literal\n"
    "        const x = a[i++];\n"
    "        switch (k) {\n"
    "          case \"s\": return typeof x === \"object\" && x !== null ? inspect(x)\n"
    "              : (typeof x === \"bigint\" ? String(x) + \"n\" : String(x));\n"
    "          case \"d\": case \"i\": {\n"
    "            if (typeof x === \"bigint\") return String(x) + \"n\";\n"
    "            const n = Number(x); return Number.isNaN(n) ? \"NaN\" : String(Math.trunc(n));\n"
    "          }\n"
    "          case \"f\": { const n = Number(x); return Number.isNaN(n) ? \"NaN\" : String(n); }\n"
    "          case \"j\": try { return JSON.stringify(x); } catch (e) { return \"[Circular]\"; }\n"
    "          case \"o\": case \"O\": return inspect(x);\n"
    "          case \"c\": return \"\";                // CSS directive: consumed, no output\n"
    "        }\n"
    "      });\n"
    "    } else {\n"
    "      out = str(first);\n"
    "    }\n"
    "    for (; i < a.length; i++) out += \" \" + str(a[i]);\n"
    "    return out;\n"
    "  }\n"
    "\n"
    "  //  The one write path: format → utf8 bytes → io.writeAll to the fd (reusing\n"
    "  //  the buf.cpp leaves; routing through io.writeAll keeps it interceptable).\n"
    "  function emit(fd, s) { io.writeAll(fd, utf8.Encode(s + \"\\n\")); }\n"
    "\n"
    "  g.console = {\n"
    "    log:   function () { emit(io.stdout, format(arguments)); },\n"
    "    info:  function () { emit(io.stdout, format(arguments)); },\n"
    "    debug: function () { emit(io.stdout, format(arguments)); },\n"
    "    warn:  function () { emit(io.stderr, format(arguments)); },\n"
    "    error: function () { emit(io.stderr, format(arguments)); },\n"
    "    trace: function () { emit(io.stderr, \"Trace: \" + format(arguments)); },\n"
    "    dir:   function (obj) { emit(io.stdout, inspect(obj)); },\n"
    "    assert: function (cond) {\n"
    "      if (cond) return;\n"
    "      const rest = Array.prototype.slice.call(arguments, 1);\n"
    "      emit(io.stderr, rest.length ? \"Assertion failed: \" + format(rest) : \"Assertion failed\");\n"
    "    },\n"
    "  };\n"
    "})(this);\n";

ok64 JABCInstallConsole(JSContext *ctx, JSValueConst global) {
    (void)ctx;
    (void)global;
    JABCExecute(JABC_CONSOLE_JS);
    return OK;
}
