//  JAB-036: cont.c — the port of jab/cont.cpp + cont.hpp.  It OWNS the global
//  `abc` object every container binding (heap..weave) attaches to.
//
//  The container framework: per-(family,lane) prototypes whose verbs are bound
//  once to the native _heap_*/_hash_* leaves, plus the all-mmap constructors
//  (abc.ram / abc.mmap / abc.over).  A container IS a lane-typed view over a
//  JS-owned mapping; the cursor (watermark) rides on its ArrayBuffer; close()
//  drops the pin and lets GC munmap.  Embedded as a C string literal (C has no
//  raw strings — the one textual difference from jab's bundle, plus the
//  by-name leaf binding the split-module install order forces, see LEAF below).
#include "JABC.h"

static const char *JABC_CONT_JS =
    "\n"
    "(function (g) {\n"
    "  \"use strict\";\n"
    "  const abc = g.abc, io = g.io, utf8 = g.utf8;\n"
    "\n"
    "  //  lane -> { typed-array ctor, JS elems per slot, pair?, bigint? }\n"
    "  const LANE = {\n"
    "    u8:    { A: Uint8Array,     w: 1, pair: false, big: false },\n"
    "    u16:   { A: Uint16Array,    w: 1, pair: false, big: false },\n"
    "    u32:   { A: Uint32Array,    w: 1, pair: false, big: false },\n"
    "    u64:   { A: BigUint64Array, w: 1, pair: false, big: true  },\n"
    "    kv32:  { A: Uint32Array,    w: 2, pair: true,  big: false },\n"
    "    kv64:  { A: BigUint64Array, w: 2, pair: true,  big: true  },\n"
    "    wh64:  { A: BigUint64Array, w: 1, pair: false, big: true  },\n"
    "    wh128: { A: BigUint64Array, w: 2, pair: true,  big: true, set: true },\n"
    "    sha1:   { A: Uint8Array, w: 20, pair: false, big: false, blob: true },\n"
    "    sha256: { A: Uint8Array, w: 32, pair: false, big: false, blob: true },\n"
    "  };\n"
    "  //  JAB-036: every container binding is its OWN module now and installs\n"
    "  //  AFTER cont (main.c order), so a leaf is bound by NAME and looked up\n"
    "  //  at call time — the very idiom the HUNK/PACK/ULOG protos below use.\n"
    "  const LEAF = (n) => (...a) => abc[n](...a);\n"
    "  const PROTO = {};\n"
    "  const laneOf = (fam) => fam.slice(4);   // strip \"HEAP\"/\"HASH\" (4 chars)\n"
    "\n"
    "  for (const lane in LANE) {\n"
    "    const M = LANE[lane];\n"
    "    //  HEAP: push/pop/peek/size, cursor on buffer.watermark\n"
    "    {\n"
    "      const push = LEAF(\"_heap_\" + lane + \"_push\");\n"
    "      const pop  = LEAF(\"_heap_\" + lane + \"_pop\");\n"
    "      const feed = LEAF(\"_heap_\" + lane + \"_feed\");\n"
    "      const p = Object.create(M.A.prototype);\n"
    "      p.push = M.pair\n"
    "        ? function (k, v) { this.buffer.watermark = push(this, this.buffer.watermark, k, v); return this; }\n"
    "        : function (v)    { this.buffer.watermark = push(this, this.buffer.watermark, v);    return this; };\n"
    "      //  JS-106: bulk push of a contiguous entries view, one native call.\n"
    "      p.feed = function (v) { this.buffer.watermark = feed(this, this.buffer.watermark, v); return this; };\n"
    "      p.pop = function () {\n"
    "        if (this.buffer.watermark === 0) return undefined;\n"
    "        const r = pop(this, this.buffer.watermark);\n"
    "        this.buffer.watermark--;\n"
    "        return r;\n"
    "      };\n"
    "      p.peek = M.blob\n"
    "        ? function () { return this.buffer.watermark ? this.subarray(0, M.w) : undefined; }\n"
    "        : M.pair\n"
    "        ? function () { return this.buffer.watermark ? [this[0], this[1]] : undefined; }\n"
    "        : function () { return this.buffer.watermark ? this[0] : undefined; };\n"
    "      Object.defineProperty(p, \"size\", { get() { return this.buffer.watermark; } });\n"
    "      p.lane = lane;                                   // type tag for sort/merge\n"
    "      const sort = LEAF(\"_sort_\" + lane);            // QSORTx leaf, by lane Z\n"
    "      p.sort = function () { sort(this, this.buffer.watermark); return this; };\n"
    "      PROTO[\"HEAP\" + lane] = p;\n"
    "    }\n"
    "    //  HASH: open-addressed table over the whole (zeroed, pow2) region\n"
    "    {\n"
    "      const put = LEAF(\"_hash_\" + lane + \"_put\");\n"
    "      const get = LEAF(\"_hash_\" + lane + \"_get\");\n"
    "      const del = LEAF(\"_hash_\" + lane + \"_del\");\n"
    "      const p = Object.create(M.A.prototype);\n"
    "      if (M.blob) {\n"
    "        //  set of fixed-size byte blobs (sha1/sha256): key == the whole blob\n"
    "        p.put = function (b) { put(this, b); return this; };\n"
    "        p.get = function (b) { return get(this, b); };\n"
    "        p.has = function (b) { return this.get(b) !== undefined; };\n"
    "        p.del = function (b) { del(this, b); return this; };\n"
    "      } else if (M.set) {\n"
    "        //  set of (key,val) pairs (wh128): lookups supply both fields\n"
    "        p.put = function (k, v) { put(this, k, v); return this; };\n"
    "        p.get = function (k, v) { return get(this, k, v); };\n"
    "        p.has = function (k, v) { return this.get(k, v) !== undefined; };\n"
    "        p.del = function (k, v) { del(this, k, v); return this; };\n"
    "      } else if (M.pair) {\n"
    "        //  key -> val map (kv32/kv64)\n"
    "        p.put = function (k, v) { put(this, k, v); return this; };\n"
    "        p.get = function (k) { return get(this, k); };\n"
    "        p.has = function (k) { return this.get(k) !== undefined; };\n"
    "        p.del = function (k) { del(this, k); return this; };\n"
    "      } else {\n"
    "        //  set of scalars (get returns the value iff present)\n"
    "        p.put = function (v) { put(this, v); return this; };\n"
    "        p.get = function (v) { return get(this, v); };\n"
    "        p.has = function (v) { return this.get(v) !== undefined; };\n"
    "        p.del = function (v) { del(this, v); return this; };\n"
    "      }\n"
    "      PROTO[\"HASH\" + lane] = p;\n"
    "    }\n"
    "  }\n"
    "\n"
    "  //  HUNK: a u8-backed log of TLV 'H' records (not a lane).  The object IS the\n"
    "  //  cursor — `next()` advances the read pos and the field getters reflect the\n"
    "  //  current record (zero-copy views into the one buffer).\n"
    "  {\n"
    "    const EMPTY8 = new Uint8Array(0), EMPTY32 = new Uint32Array(0);\n"
    "    const P = Object.create(Uint8Array.prototype);\n"
    "    P.feed = function (uri, text, toks) {\n"
    "      this.buffer.watermark = abc._hunk_feed(this, this.buffer.watermark,\n"
    "        uri, text || EMPTY8, toks || EMPTY32);\n"
    "      return this;\n"
    "    };\n"
    "    P.dogenize = function (src, ext, uri) {     // tokenize source -> append a hunk\n"
    "      this.buffer.watermark = abc._hunk_dogenize(this, this.buffer.watermark,\n"
    "        src, ext, uri || \"\");\n"
    "      return this;\n"
    "    };\n"
    "    P.rewind = function () { this._read = 0; this._rec = -1; return this; };\n"
    "    P.next = function () {\n"
    "      const e = abc._hunk_next(this, this._read | 0, this.buffer.watermark | 0);\n"
    "      if (e < 0) return false;\n"
    "      this._rec = this._read | 0; this._read = e; return true;\n"
    "    };\n"
    "    Object.defineProperty(P, \"uri\",  { get() { return abc._hunk_uri(this, this._rec); } });\n"
    "    Object.defineProperty(P, \"text\", { get() { return abc._hunk_text(this, this._rec); } });\n"
    "    Object.defineProperty(P, \"toks\", { get() { return abc._hunk_toks(this, this._rec); } });\n"
    "    Object.defineProperty(P, \"verb\", { get() { return abc._hunk_verb(this, this._rec); } });\n"
    "    Object.defineProperty(P, \"time\", { get() { return abc._hunk_time(this, this._rec); } });\n"
    "    //  `out` is an io.buf Buf (the buf.cpp cursor): render into its IDLE, then\n"
    "    //  commit with fed().\n"
    "    const render = (mode) => function (out) {\n"
    "      out.fed(abc._hunk_render(this, this._rec, out.idle(), 0, mode));\n"
    "      return out;\n"
    "    };\n"
    "    P.color = render(1);\n"
    "    P.plain = render(2);\n"
    "    P.html = render(3);\n"
    "    PROTO[\"HUNK\"] = P;\n"
    "  }\n"
    "\n"
    "  //  git.pack PROTO: an offset-addressed git pack log (u8).  feed returns the\n"
    "  //  object's byte offset; seek/next address by offset only (a sha throws);\n"
    "  //  delta records are surfaced (baseOffset/ref), not resolved.  JS-024: this\n"
    "  //  is NOT an abc family — the `git` package below owns its constructors.\n"
    "  const PACK_PROTO = (function () {\n"
    "    const T2N = { commit: 1, tree: 2, blob: 3, tag: 4, \"ofs-delta\": 6, \"ref-delta\": 7 };\n"
    "    const N2T = { 1: \"commit\", 2: \"tree\", 3: \"blob\", 4: \"tag\", 6: \"ofs-delta\", 7: \"ref-delta\" };\n"
    "    const EMPTY8 = new Uint8Array(0);\n"
    "    const P = Object.create(Uint8Array.prototype);\n"
    "    //  JS-055: size scratch off the RECORD's resolved size (a compressible\n"
    "    //  object can inflate past the pack); `_dsc` is split, so ~2x `_bsc`.\n"
    "    const SCRATCH_MIN = 1 << 16;\n"
    "    P._scratch = function (need) {\n"
    "      let n = need ? (need | 0) : SCRATCH_MIN;\n"
    "      if (n < SCRATCH_MIN) n = SCRATCH_MIN;\n"
    "      if (!this._bsc || this._bsc.byteLength < n) {\n"
    "        this._bsc = new Uint8Array(n);     // base scratch (resolved bytes)\n"
    "        this._dsc = new Uint8Array(2 * n); // delta scratch (split internally)\n"
    "      }\n"
    "    };\n"
    "    //  JS-055: re-run `op` doubling scratch on the binding's NOROOM throw; any\n"
    "    //  other error (ref-delta, corruption) propagates; capped against a loop.\n"
    "    P._grow = function (need, op) {\n"
    "      this._scratch(need);\n"
    "      for (let tries = 0; tries < 40; tries++) {\n"
    "        try { return op(); }\n"
    "        catch (e) {\n"
    "          if (!(\"\" + e).includes(\"NOROOM\")) throw e;\n"
    "          this._scratch(this._bsc.byteLength * 2);\n"
    "        }\n"
    "      }\n"
    "      throw \"pack: scratch exhausted\";\n"
    "    };\n"
    "    P.header = function () {\n"
    "      this.buffer.watermark = abc._pack_header(this, 0, 0);\n"
    "      this._count = 0; this._read = 12; this._rec = -1;\n"
    "      return this;\n"
    "    };\n"
    "    P.feed = function (type, content, prevOff, out) {\n"
    "      const off = this.buffer.watermark;\n"
    "      const t = (typeof type === \"number\") ? type : T2N[type];\n"
    "      //  Resolve the base to its full bytes by offset (the read path); the\n"
    "      //  dog/git writer decides OFS_DELTA vs raw from base+content.\n"
    "      let base = EMPTY8, bo = -1;\n"
    "      if (prevOff != null && prevOff >= 0) {\n"
    "        //  JS-055: size off the base's declared resolved size; grow on NOROOM.\n"
    "        base = this._grow(abc._pack_size(this, prevOff),\n"
    "          () => abc._pack_resolve(this, prevOff, this._bsc, this._dsc));\n"
    "        bo = prevOff;\n"
    "      }\n"
    "      //  delta-encode scratch must hold a delta no larger than `content`.\n"
    "      this._scratch(content.length);\n"
    "      this.buffer.watermark = abc._pack_feed(this, off, t, content, base, bo, this._dsc);\n"
    "      this._count = (this._count | 0) + 1;\n"
    "      //  GIT-010 index-on-append: if given an `out` entry sink (a Buf), drop\n"
    "      //  the just-fed object's (sha->offset) wh128 entry in — git-sha the\n"
    "      //  content we already hold, no resolve.  The pack-log owns no index.\n"
    "      if (out != null) {\n"
    "        const idle = out.idle();\n"
    "        const n = abc._pack_feed_emit(t, content, off, idle, 0);\n"
    "        out.fed(n);\n"
    "      }\n"
    "      return off;\n"
    "    };\n"
    "    //  resolve(out): chase this record's delta chain to full bytes via the\n"
    "    //  dog/git resolver, append them to the `out` Buf.\n"
    "    P.resolve = function (out) {\n"
    "      //  JS-055: presize off the record's declared size, grow on NOROOM.\n"
    "      const b = this._grow(abc._pack_size(this, this._rec),\n"
    "        () => abc._pack_resolve(this, this._rec, this._bsc, this._dsc));\n"
    "      out.feed(b);\n"
    "      return out;\n"
    "    };\n"
    "    //  scan(out): GIT-010 index-EMIT — walk the WHOLE pack, resolve+git-sha\n"
    "    //  each object, and drop one wh128 `(key=hashlet60|type, val=offset)`\n"
    "    //  entry per object into the `out` Buf's IDLE via the dog/git PIDXScan.\n"
    "    //  Advances out by n*16 bytes and returns a ZERO-COPY BigUint64Array view\n"
    "    //  (n*2 u64s: key,val,key,val,...) over the bytes just written — the\n"
    "    //  caller pipes them into an abc.index wh128 lane (idx.put(key, val)).\n"
    "    //  The pack-log owns NO index: sort/merge/persist/query is the caller's.\n"
    "    P.scan = function (out) {\n"
    "      //  JS-055: an object's inflated size can exceed the pack; the per-object\n"
    "      //  max isn't known up front, so grow the scratch on NOROOM and re-scan.\n"
    "      const idle = out.idle();\n"
    "      const n = this._grow(0,\n"
    "        () => abc._pack_scan(this, this.buffer.watermark | 0, idle, this._bsc, this._dsc));\n"
    "      out.fed(n * 16);                       // n wh128 entries (16 B each)\n"
    "      return new BigUint64Array(idle.buffer, idle.byteOffset, n * 2);\n"
    "    };\n"
    "    P.finish = function () { abc._pack_header(this, 0, this._count | 0); return this; };\n"
    "    P.rewind = function () { this._read = 12; this._rec = -1; return this; };\n"
    "    P.next = function () {\n"
    "      const e = abc._pack_next(this, this._read | 0, this.buffer.watermark | 0);\n"
    "      if (e < 0) return false;\n"
    "      this._rec = this._read | 0; this._read = e; return true;\n"
    "    };\n"
    "    P.seek = function (off) {\n"
    "      if (typeof off !== \"number\") throw \"PACK addresses by offset, not sha\";\n"
    "      const e = abc._pack_next(this, off, this.buffer.watermark | 0);\n"
    "      //  PTR-010: a rejected offset UNPOSITIONS the cursor — leaving the old\n"
    "      //  `_rec` (or the initial -1) is what fed -1 to the size getter and\n"
    "      //  read a byte below the mapping.  Callers that ignore `false` now see\n"
    "      //  undefined, not a wild read.\n"
    "      if (e < 0) { this._rec = -1; return false; }\n"
    "      this._rec = off; this._read = e; return true;\n"
    "    };\n"
    "    //  Positioned? Every record getter is undefined on an unpositioned cursor.\n"
    "    P._at = function () { return (this._rec | 0) >= 0; };\n"
    "    Object.defineProperty(P, \"count\", { get() { return abc._pack_count(this); } });\n"
    "    Object.defineProperty(P, \"offset\", { get() { return this._rec; } });\n"
    "    Object.defineProperty(P, \"type\", {\n"
    "      get() { return this._at() ? N2T[abc._pack_type(this, this._rec)] : undefined; }\n"
    "    });\n"
    "    Object.defineProperty(P, \"size\", {\n"
    "      get() { return this._at() ? abc._pack_size(this, this._rec) : undefined; }\n"
    "    });\n"
    "    Object.defineProperty(P, \"baseOffset\", {\n"
    "      get() {\n"
    "        if (!this._at()) return undefined;\n"
    "        const b = abc._pack_baseoff(this, this._rec); return b < 0 ? undefined : b;\n"
    "      }\n"
    "    });\n"
    "    Object.defineProperty(P, \"ref\", {\n"
    "      get() { return this._at() ? abc._pack_ref(this, this._rec) : undefined; }\n"
    "    });\n"
    "    P.inflate = function (out) {\n"
    "      out.fed(abc._pack_inflate(this, this._rec, out.idle(), 0));\n"
    "      return out;\n"
    "    };\n"
    "    return P;\n"
    "  })();\n"
    "\n"
    "  //  ULOG: append-only (ts,verb,uri) text log, no index.  feed moves the\n"
    "  //  watermark; seek* are pure offset->offset scans (fwd, or rev from .end).\n"
    "  {\n"
    "    const P = Object.create(Uint8Array.prototype);\n"
    "    P.feed = function (verb, uri, ts) {\n"
    "      let t = (ts == null) ? abc._ulog_now() : BigInt(ts);\n"
    "      if (this._lastTs != null && t <= this._lastTs) t = this._lastTs + 1n;  // monotonic\n"
    "      this._lastTs = t;\n"
    "      const off = this.buffer.watermark;\n"
    "      this.buffer.watermark = abc._ulog_feed(this, off, verb, uri, t);\n"
    "      return off;\n"
    "    };\n"
    "    P.rewind = function () { this._read = 0; this._rec = -1; return this; };\n"
    "    P.next = function () {\n"
    "      const e = abc._ulog_next(this, this._read | 0, this.buffer.watermark | 0);\n"
    "      if (e < 0) return false;\n"
    "      this._rec = this._read | 0; this._read = e; return true;\n"
    "    };\n"
    "    P.seek = function (off) {\n"
    "      if (typeof off !== \"number\") throw \"ULOG addresses by offset\";\n"
    "      const e = abc._ulog_next(this, off, this.buffer.watermark | 0);\n"
    "      if (e < 0) return false;\n"
    "      this._rec = off; this._read = e; return true;\n"
    "    };\n"
    "    Object.defineProperty(P, \"end\", { get() { return this.buffer.watermark; } });\n"
    "    Object.defineProperty(P, \"after\", { get() { return this._read; } });\n"
    "    Object.defineProperty(P, \"offset\", { get() { return this._rec; } });\n"
    "    Object.defineProperty(P, \"time\", { get() { return abc._ulog_time(this, this._rec); } });\n"
    "    Object.defineProperty(P, \"verb\", { get() { return abc._ulog_verb(this, this._rec); } });\n"
    "    Object.defineProperty(P, \"uri\", { get() { return abc._ulog_uri(this, this._rec); } });\n"
    "    const mkseek = (leaf, rev) => function (off, arg) {\n"
    "      const o = abc[leaf](this, off, this.buffer.watermark | 0, arg, rev);\n"
    "      if (o >= 0) this.seek(o);            // position cursor on a hit\n"
    "      return o;\n"
    "    };\n"
    "    P.seekVerb = mkseek(\"_ulog_seekVerb\", false);\n"
    "    P.seekVerbRev = mkseek(\"_ulog_seekVerb\", true);\n"
    "    P.seekTime = mkseek(\"_ulog_seekTime\", false);\n"
    "    P.seekTimeRev = mkseek(\"_ulog_seekTime\", true);\n"
    "    P.seekURI = mkseek(\"_ulog_seekURI\", false);\n"
    "    P.seekURIRev = mkseek(\"_ulog_seekURI\", true);\n"
    "    PROTO[\"ULOG\"] = P;\n"
    "  }\n"
    "\n"
    "  //  CFOLD (DIS-082): one file's whole DAG history as a 'V' TLV blob in a u8\n"
    "  //  buffer — the APPEND-ONLY weave.  Parsed zero-copy per call; fold()/merge()\n"
    "  //  rewrite the WHOLE blob.  Commit ids are 16-char hex hashlet strings (the\n"
    "  //  hi64 of the commit sha1) and every rev argument is one of them: visibility\n"
    "  //  is STORED per commit, so no scope bitmaps and no token cursor exist.\n"
    "  {\n"
    "    const P = Object.create(Uint8Array.prototype);\n"
    "    P.empty = function () { return abc._cfold_count(this, this.buffer.watermark | 0) === 0; };\n"
    "    //  size = the 'E' INDEX entry count (inserts + tombs + chain terminators),\n"
    "    //  not the visible-token count; tokens() answers that per rev.\n"
    "    Object.defineProperty(P, \"size\",\n"
    "      { get() { return abc._cfold_count(this, this.buffer.watermark | 0); } });\n"
    "    Object.defineProperty(P, \"commits\",\n"
    "      { get() { return abc._cfold_commits(this, this.buffer.watermark | 0); } });\n"
    "    //  builders rewrite THIS buffer; base is another CFOLD container (or null\n"
    "    //  for the first revision).  blob is file bytes (Uint8Array or Buf), and\n"
    "    //  `ancestors` is the commit's whole causal closure (itself excluded).\n"
    "    const bytesOf = (x) => (x && typeof x.data === \"function\") ? x.data() : x;\n"
    "    P.fold = function (base, blob, ext, hash, ancestors) {\n"
    "      const bl = base ? (base.buffer.watermark | 0) : 0;\n"
    "      this.buffer.watermark = abc._cfold_next(this, base || null, bl,\n"
    "        bytesOf(blob), ext, hash, ancestors || []);\n"
    "      return this;\n"
    "    };\n"
    "    //  a merge carries no content: ONE already-folded weave in, one commit\n"
    "    //  record out with the intersected ignore-set.\n"
    "    P.merge = function (base, hash, ancestors) {\n"
    "      this.buffer.watermark = abc._cfold_merge(this, base,\n"
    "        base.buffer.watermark | 0, hash, ancestors || []);\n"
    "      return this;\n"
    "    };\n"
    "    P.alive = function (out) {\n"
    "      out.fed(abc._cfold_alive(this, this.buffer.watermark | 0, out.idle()));\n"
    "      return out;\n"
    "    };\n"
    "    P.produce = function (rev, out) {\n"
    "      out.fed(abc._cfold_produce(this, this.buffer.watermark | 0, rev, out.idle()));\n"
    "      return out;\n"
    "    };\n"
    "    //  which commit inserted the token at body offset `off` -> its hashlet.\n"
    "    P.blame = function (off) {\n"
    "      return abc._cfold_blame(this, this.buffer.watermark | 0, off | 0);\n"
    "    };\n"
    "    //  the per-token cursor (the iteration API): rewind(rev) arms a JS-owned\n"
    "    //  cursor, next() steps once and sets this.tok — text (a view into this\n"
    "    //  blob), tag, off/end (BODY offsets: feed off to blame()), alive.\n"
    "    P.rewind = function (rev) {\n"
    "      this._rev = rev;\n"
    "      this._cur = new Uint32Array(\n"
    "          abc._cfold_itermem(this, this.buffer.watermark | 0));\n"
    "      return this;\n"
    "    };\n"
    "    P.next = function () {\n"
    "      const t = abc._cfold_step(this, this.buffer.watermark | 0,\n"
    "                                this._rev, this._cur);\n"
    "      if (!t) return false;\n"
    "      this.tok = t;\n"
    "      return true;\n"
    "    };\n"
    "    //  diff from-rev -> to-rev (commit hashlets) as HUNK records appended into\n"
    "    //  a HUNK container `hunk` (toks carry the per-token diff side); read/render\n"
    "    //  it with the HUNK cursor (next()/uri/text/toks/plain/color/html).\n"
    "    P.emitDiff = function (from, to, name, navver, hunk) {\n"
    "      hunk.buffer.watermark = abc._cfold_emitdiff(this, this.buffer.watermark | 0,\n"
    "        name || \"\", navver || \"\", from, to, hunk, hunk.buffer.watermark | 0);\n"
    "      return hunk;\n"
    "    };\n"
    "    P.emitFull = function (from, to, name, scheme, navver, hunk) {\n"
    "      hunk.buffer.watermark = abc._cfold_emitfull(this, this.buffer.watermark | 0,\n"
    "        name || \"\", scheme || \"\", navver || \"\", from, to, hunk, hunk.buffer.watermark | 0);\n"
    "      return hunk;\n"
    "    };\n"
    "    PROTO[\"CFOLD\"] = P;\n"
    "  }\n"
    "\n"
    "  const isLog = (f) => f === \"HUNK\" || f === \"ULOG\" || f === \"CFOLD\";   // u8-backed\n"
    "\n"
    "  function build(family, u8) {\n"
    "    const proto = PROTO[family];\n"
    "    if (!proto) throw \"abc: unknown family \" + family;\n"
    "    let v;\n"
    "    if (isLog(family)) {                // u8-backed log: use the byte view directly\n"
    "      v = u8;\n"
    "      Object.setPrototypeOf(v, proto);\n"
    "      v._read = 0;\n"
    "      v._rec = -1;\n"
    "    } else {\n"
    "      const M = LANE[laneOf(family)];\n"
    "      if (!M) throw \"abc: unknown family \" + family;\n"
    "      v = new M.A(u8.buffer, u8.byteOffset, (u8.byteLength / M.A.BYTES_PER_ELEMENT) | 0);\n"
    "      Object.setPrototypeOf(v, proto);   // real typed array + the family's verbs\n"
    "    }\n"
    "    v.buffer._map = u8;                // pin the mapping (munmap on GC)\n"
    "    v.buffer.watermark = 0;\n"
    "    return v;\n"
    "  }\n"
    "  const bytes = (family, slots) => {\n"
    "    if (isLog(family)) return slots;              // u8 bytes\n"
    "    const M = LANE[laneOf(family)];\n"
    "    return slots * M.w * M.A.BYTES_PER_ELEMENT;\n"
    "  };\n"
    "\n"
    "  abc.ram  = (family, slots) => build(family, io._ram(bytes(family, slots)));\n"
    "  abc.mmap = (family, path, mode, slots) => {\n"
    "    mode = mode || \"rw\";\n"
    "    return build(family, io._mmap(path, mode, mode === \"c\" ? bytes(family, slots || 0) : 0));\n"
    "  };\n"
    "  abc.over = (family, ta) => build(family,\n"
    "    (ta instanceof Uint8Array) ? ta : new Uint8Array(ta.buffer, ta.byteOffset, ta.byteLength));\n"
    "\n"
    "  //  book: a file-backed output sized to an upper bound (cheap — sparse), to\n"
    "  //  be filled (e.g. by merge) and trimmed to the live size on close.\n"
    "  abc.book = (family, path, slots) => {\n"
    "    const c = build(family, io._mmap(path, \"c\", bytes(family, slots)));\n"
    "    c.buffer._path = path;\n"
    "    return c;\n"
    "  };\n"
    "  abc.close = (c) => {\n"
    "    const b = c.buffer;\n"
    "    let trim = -1;\n"
    "    if (b._path) {                                  // booked: trim file to live size\n"
    "      const M = LANE[c.lane];\n"
    "      //  a PACK book (git.pack.book) has no .lane: it's a u8 log written\n"
    "      //  start-to-end, so trim to the write head (watermark), no lane scaling.\n"
    "      trim = M ? (c.size | 0) * M.w * M.A.BYTES_PER_ELEMENT : (b.watermark | 0);\n"
    "    }\n"
    "    //  ABC-020: detach FIRST (msync would materialize the buffer and defeat\n"
    "    //  transfer's move) so stale views read empty, then flush+trim+release the\n"
    "    //  fd+mapping NOW off the moved husk; double close is a harmless no-op.\n"
    "    //  ABC-023: a read-only map holds no fd and no slot — close just detaches\n"
    "    //  the views here, the pages go back at GC; _munmap finds nothing, no error.\n"
    "    let husk;\n"
    "    try { husk = b.transfer(); } catch (e) { return; }\n"
    "    const view = new Uint8Array(husk);\n"
    "    try { io._msync(view); } catch (e) {}\n"
    "    if (trim >= 0) io._truncate(b._path, trim);\n"
    "    io._munmap(view);\n"
    "    b._map = null;\n"
    "  };\n"
    "\n"
    "  //  HIT bulk ops over SORTED runs.  Inputs are containers (each carries its\n"
    "  //  .lane and .size); the lane is read off the operands (no type arg), all\n"
    "  //  must agree.  Without `out` a fresh lane-typed run is returned; with `out`\n"
    "  //  (a container sized to >= Sum of inputs) the result is written in place and\n"
    "  //  out.size is set, so it can be trimmed on close (abc.book) and re-merged.\n"
    "  const kway = (pfx, op, inputs, out) => {\n"
    "    if (!inputs.length) throw \"abc.\" + op + \": no inputs\";\n"
    "    const lane = inputs[0].lane;\n"
    "    if (!lane) throw \"abc.\" + op + \": inputs need a lane (use abc.ram/over)\";\n"
    "    const M = LANE[lane];\n"
    "    const runs = inputs.map((c) => {\n"
    "      if (c.lane !== lane) throw \"abc.\" + op + \": lane mismatch\";\n"
    "      return c.subarray(0, (c.size | 0) * M.w);     // live region only\n"
    "    });\n"
    "    if (out) {\n"
    "      if (out.lane !== lane) throw \"abc.\" + op + \": out lane mismatch\";\n"
    "      out.buffer.watermark = abc[pfx + lane](runs, out);\n"
    "      return out;\n"
    "    }\n"
    "    const u8 = abc[pfx + lane](runs);\n"
    "    return new M.A(u8.buffer, u8.byteOffset, (u8.byteLength / M.A.BYTES_PER_ELEMENT) | 0);\n"
    "  };\n"
    "  abc.merge = (inputs, out) => kway(\"_merge_\", \"merge\", inputs, out);\n"
    "  abc.intersect = (inputs, out) => kway(\"_isect_\", \"intersect\", inputs, out);\n"
    "\n"
    "  //  git: the git/pack-log package (JS-024).  `git.pack` is the offset-pure\n"
    "  //  PACK container (migrated, hard cutover, off the old abc \"PACK\" family);\n"
    "  //  `git.delta.apply` is the delta op (migrated off the old global `delt`).\n"
    "  //  The native leaves (abc._pack_* / abc._delt_apply) are UNCHANGED — `git`\n"
    "  //  only re-homes the JS surface (the SAME PACK_PROTO + delta marshalling).\n"
    "  //  A PACK is a u8-backed log: wrap the byte view, pin the mapping (munmap on\n"
    "  //  GC), skip the 12-byte header (_read = 12), cursor at -1.\n"
    "  const packBuild = (u8) => {\n"
    "    const v = u8;\n"
    "    Object.setPrototypeOf(v, PACK_PROTO);\n"
    "    v._read = 12;                    // PACK skips the 12-byte header\n"
    "    v._rec = -1;\n"
    "    v.buffer._map = u8;              // pin the mapping (munmap on GC)\n"
    "    v.buffer.watermark = 0;\n"
    "    return v;\n"
    "  };\n"
    "  //  JAB-020: `git.pack` is BOTH the container namespace (ram/over/mmap/book,\n"
    "  //  unchanged) and the one-call stream ingest: git.pack(fd, buf, shard, opts)\n"
    "  //  repacks a whole fetch into `<shard>/NNNNNNNNNN.keeper` logs inside libdog\n"
    "  //  and returns its stats — no pack byte ever reaches the JS heap.  `buf` is\n"
    "  //  a Buf (its DATA is what the pkt-line reader already ate, its `_data` /\n"
    "  //  `_idle` come back advanced); `opts.index` is the caller's wh128 region.\n"
    "  const pack = (fd, buf, shard, opts) =>\n"
    "    abc._pack_repack(fd, buf, shard, opts || {});\n"
    "  Object.assign(pack, {\n"
    "    ram:  (slots) => packBuild(io._ram(slots)),\n"
    "    over: (ta) => packBuild((ta instanceof Uint8Array) ? ta\n"
    "                            : new Uint8Array(ta.buffer, ta.byteOffset, ta.byteLength)),\n"
    "    mmap: (path, mode, slots) => {\n"
    "      mode = mode || \"rw\";\n"
    "      return packBuild(io._mmap(path, mode, mode === \"c\" ? (slots || 0) : 0));\n"
    "    },\n"
    "    //  book: a sparse file-backed log sized to an upper bound (see abc.book);\n"
    "    //  msync + unpin on abc.close (a PACK carries no .lane, so close skips the\n"
    "    //  lane-typed trim — a PACK file is written start-to-end, no truncation).\n"
    "    book: (path, slots) => {\n"
    "      const c = packBuild(io._mmap(path, \"c\", slots));\n"
    "      c.buffer._path = path;\n"
    "      return c;\n"
    "    },\n"
    "  });\n"
    "  //  git.tree(bytes[, cb]) — JS-028.  A PULL cursor over a git tree blob\n"
    "  //  `(<mode> <name>\\0<20-byte sha>)*`: ALL cursor state lives in JS (rule #4),\n"
    "  //  the native leaf abc._git_tree_next drains exactly ONE entry per call (over\n"
    "  //  dog/git GITu8sDrainTree) and reports {mode, nameStart, nameEnd, sha,\n"
    "  //  nextOff}.  .next() advances and exposes .mode (octal incl. 0o160000\n"
    "  //  gitlinks), .name (zero-copy Uint8Array subarray of the entry name), .str\n"
    "  //  (utf8.Decode of .name), .sha (40-hex); false at end.  With a callback,\n"
    "  //  drive the cursor in-frame (io.readdir style), one cb(entry) per entry.\n"
    "  class GitTree {\n"
    "    constructor(bytes) { this._b = bytes; this._off = 0; this._e = null; }\n"
    "    next() {\n"
    "      const e = abc._git_tree_next(this._b, this._off);\n"
    "      if (e === null) { this._e = null; return false; }\n"
    "      this._e = e; this._off = e.nextOff; return true;\n"
    "    }\n"
    "    get mode() { return this._e ? this._e.mode : undefined; }\n"
    "    get sha()  { return this._e ? this._e.sha : undefined; }\n"
    "    //  zero-copy name span over the SOURCE bytes (positions, not a copy).\n"
    "    get name() {\n"
    "      return this._e ? this._b.subarray(this._e.nameStart, this._e.nameEnd) : undefined;\n"
    "    }\n"
    "    get str() { return this._e ? utf8.Decode(this.name) : undefined; }\n"
    "  }\n"
    "  const gitTree = (bytes, cb) => {\n"
    "    const t = new GitTree(bytes);\n"
    "    if (cb == null) return t;\n"
    "    while (t.next()) cb(t);            // in-frame, never stashed (rule #4)\n"
    "    return undefined;\n"
    "  };\n"
    "\n"
    "  g.git = {\n"
    "    pack,\n"
    "    tree: gitTree,\n"
    "    GitTree,\n"
    "    //  parseCommit(bytes) — JS-028.  Eager {tree, parents[], foster[], author,\n"
    "    //  committer, body} over dog/git GITu8sDrainCommit + GITu8sCommitTree (no\n"
    "    //  manual framing in JS); commit objects are small so eager is fine.  tree /\n"
    "    //  parents / foster are 40-hex strings; author/committer/body are strings.\n"
    "    parseCommit: (bytes) => abc._git_parse_commit(bytes),\n"
    "    //  delta.apply(base, delta, out): reconstruct a delta target into out (Buf)\n"
    "    //  delta.encode(base, target, out): JS-036 twin — append the delta stream\n"
    "    //  into out (Buf); -1 on DELTFAIL so the caller stores raw instead.\n"
    "    delta: {\n"
    "      apply: (base, delta, out) => {\n"
    "        const n = abc._delt_apply(base, delta, out.idle(), 0);\n"
    "        out.fed(n);\n"
    "        return n;\n"
    "      },\n"
    "      encode: (base, target, out) => {\n"
    "        const n = abc._delt_encode(base, target, out.idle(), 0);\n"
    "        if (n < 0) return -1;\n"
    "        out.fed(n);\n"
    "        return n;\n"
    "      },\n"
    "    },\n"
    "  };\n"
    "\n"
    "  //  abc.index(lane, {dir, ext, mem, durable}) — a HANDLE on a dog Pup stack\n"
    "  //  (DOG-027).\n"
    "  //  The LSM itself lives in C: `<dir>` holds the immutable oldest-first runs\n"
    "  //  (`<10-RON64><ext>`) plus the `<ext>` memtable, and every seal ends in the\n"
    "  //  1/8 ladder, so nothing here knows or decides when a compaction happens.\n"
    "  //\n"
    "  //  This INVERTS API.md rule #4 for this subsystem, deliberately: the state is\n"
    "  //  C-side (a kv64b dict behind the handle) and JS marshals only.  `dir` and\n"
    "  //  `ext` ride the object as plain JS strings and go back down on every call\n"
    "  //  that touches the filesystem.\n"
    "  //\n"
    "  //  put / commit / get / range / seek / count / run / drop / close — that IS\n"
    "  //  the surface.  `runs`, `_seq`, `mem`, `flush` and `compact` are GONE: the\n"
    "  //  run naming, the memtable, the sort and the k-way merge are one C layer.\n"
    "  //  The family writes its marker row and calls commit(); run(i)/drop(i) are\n"
    "  //  the audit path for a run whose marker is missing.\n"
    "  //\n"
    "  //  Lanes: kv64 (keyed: newest wins per key), wh128 ((key,val) rows, point on\n"
    "  //  key) and u64 (scalar).  Reopening a dir written by an older jab works:\n"
    "  //  padStart-named runs sort before every ron64 name, which is their correct\n"
    "  //  age slot, and the C scan loads whatever matches `<seqno><ext>`.\n"
    "  const IDX = {\n"
    "    kv64:  { pair: true  },\n"
    "    wh128: { pair: true  },\n"
    "    u64:   { pair: false },\n"
    "  };\n"
    "  abc.index = (lane, opts) => {\n"
    "    const M = IDX[lane];\n"
    "    if (!M) throw \"abc.index: unsupported lane \" + lane + \" (u64 | kv64 | wh128)\";\n"
    "    opts = opts || {};\n"
    "    const dir = opts.dir;\n"
    "    if (dir == null) throw \"abc.index: an index needs a dir\";\n"
    "    const ext = opts.ext || (\".\" + lane);\n"
    "    io.mkdir(dir);\n"
    "    const L = (verb) => abc[\"_pup_\" + lane + \"_\" + verb];\n"
    "    const _put = L(\"put\"), _commit = L(\"commit\"), _get = L(\"get\"),\n"
    "          _range = L(\"range\"), _seek = L(\"seek\"), _next = L(\"next\"),\n"
    "          _count = L(\"count\"), _run = L(\"run\"), _drop = L(\"drop\"),\n"
    "          _close = L(\"close\");\n"
    "\n"
    "    //  DOG-032: `opts.mem` is the memtable's ROW capacity (rounded UP to whole\n"
    "    //  OS pages, 0/absent = one page) and `opts.durable === false` makes a seal\n"
    "    //  skip its fsync — the bulk-index pair.  `idx.mem` reads the rounded rows.\n"
    "    const idx = { lane, dir, ext,\n"
    "                  _h: L(\"open\")(dir, ext, opts.mode || \"rw\", opts.mem || 0) };\n"
    "    idx.mem = abc._pup_mem(idx._h);\n"
    "    const _durable = opts.durable !== false;\n"
    "\n"
    "    //  put: append to the memtable; a full page seals a run + runs the ladder.\n"
    "    idx.put = M.pair\n"
    "      ? function (k, v) { _put(this._h, this.dir, this.ext, BigInt(k), BigInt(v)); return this; }\n"
    "      : function (v)    { _put(this._h, this.dir, this.ext, BigInt(v)); return this; };\n"
    "    //  JS-106: bulk put of a contiguous entries view (pack.scan's shape).\n"
    "    idx.feed = M.pair\n"
    "      ? function (view) { for (let i = 0; i + 1 < view.length; i += 2) this.put(view[i], view[i + 1]); return this; }\n"
    "      : function (view) { for (let i = 0; i < view.length; i++) this.put(view[i]); return this; };\n"
    "\n"
    "    //  commit: the family put its marker row first; C collapses, seals, and\n"
    "    //  compacts.  The rename is atomic, so a crash leaves no half-run.\n"
    "    //  commit(durable) overrides the handle's default for the ONE final seal.\n"
    "    idx.commit = function (durable) {\n"
    "      _commit(this._h, this.dir, this.ext,\n"
    "              durable === undefined ? _durable : !!durable);\n"
    "      return this;\n"
    "    };\n"
    "\n"
    "    //  point lookup, newest wins (the memtable shadows the runs).\n"
    "    idx.get = function (k) { return _get(this._h, BigInt(k)); };\n"
    "\n"
    "    //  ordered [lo, hi) scan through an in-frame cb; \"enough\"/false stops it.\n"
    "    idx.range = function (lo, hi, cb) { _range(this._h, BigInt(lo), BigInt(hi), cb); return this; };\n"
    "    //  prefix(p, lowBits) == range [p, p + 2^lowBits) — the keeper/spot block.\n"
    "    idx.prefix = function (p, lowBits, cb) {\n"
    "      const lo = BigInt(p);\n"
    "      return this.range(lo, lo + (1n << BigInt(lowBits | 0)), cb);\n"
    "    };\n"
    "\n"
    "    //  seek(k): a merged pull cursor at the first row >= k.  The cursor state\n"
    "    //  is the handle's (one at a time); .next() pulls ONE merged row.\n"
    "    idx.seek = function (k) {\n"
    "      const H = this._h;\n"
    "      _seek(H, BigInt(k));\n"
    "      const cur = { key: undefined, val: undefined, entry: undefined };\n"
    "      cur.next = M.pair\n"
    "        ? function () {\n"
    "            const e = _next(H);\n"
    "            if (e === undefined) { this.key = this.val = this.entry = undefined; return false; }\n"
    "            this.key = e[0]; this.val = e[1]; this.entry = e;\n"
    "            return true;\n"
    "          }\n"
    "        : function () {\n"
    "            const v = _next(H);\n"
    "            if (v === undefined) { this.key = this.val = this.entry = undefined; return false; }\n"
    "            this.key = this.val = this.entry = v;\n"
    "            return true;\n"
    "          };\n"
    "      return cur;\n"
    "    };\n"
    "\n"
    "    //  count: committed runs (the memtable is not one).\n"
    "    Object.defineProperty(idx, \"count\", { get() { return _count(this._h); } });\n"
    "\n"
    "    //  run(i): a read-only lane-typed view of run i, oldest-first — the\n"
    "    //  family's marker audit.  It borrows the C mapping, so QJAB-006 ties it\n"
    "    //  to the handle: put/commit/drop/close DETACH it (as abc.close detaches\n"
    "    //  its own views) and a view held across one reads empty, length 0.\n"
    "    idx.run = function (i) {\n"
    "      const u = _run(this._h, i);\n"
    "      return new BigUint64Array(u.buffer, u.byteOffset, (u.byteLength / 8) | 0);\n"
    "    };\n"
    "    //  drop(i): unlink a markerless run; drop() drops them all (re-derive).\n"
    "    idx.drop = function (i) {\n"
    "      if (i === undefined) _drop(this._h, this.dir, this.ext);\n"
    "      else _drop(this._h, this.dir, this.ext, i);\n"
    "      return this;\n"
    "    };\n"
    "    //  close: munmap the runs + the memtable, free the dict.\n"
    "    idx.close = function () { _close(this._h); return this; };\n"
    "\n"
    "    return idx;\n"
    "  };\n"
    "})(this);\n";

//  jab's cont.cpp runs the bundle after calling the container installs inline;
//  here main.c drives them, so cont only creates `abc` and loads the JS.
ok64 JABCInstallCont(JSContext *ctx, JSValueConst global) {
    JABC_API_OBJECT(abc);
    JABC_API_END(abc);
    JABCExecute(JABC_CONT_JS);
    return OK;
}
