//  JAB-036: jab/require.cpp — the synchronous CommonJS require(), a pure
//  embedded-JS bundle (GET-041 jsrc stack + JAB-035 pack floor), verbatim.
#include "JABC.h"

static const char *JABC_REQUIRE_JS =
    "(function (g) {\n"
    "  \"use strict\";\n"
    "  const io = g.io, utf8 = g.utf8;\n"
    "  const cache = {};\n"
    "\n"
    "  function normalize(p) {\n"
    "    const abs = p[0] === \"/\";\n"
    "    const out = [];\n"
    "    for (const s of p.split(\"/\")) {\n"
    "      if (s === \"\" || s === \".\") continue;\n"
    "      if (s === \"..\") {\n"
    "        if (out.length && out[out.length - 1] !== \"..\") out.pop();\n"
    "        else if (!abs) out.push(\"..\");\n"
    "      } else out.push(s);\n"
    "    }\n"
    "    return (abs ? \"/\" : \"\") + out.join(\"/\");\n"
    "  }\n"
    "  function dirname(p) {\n"
    "    const i = p.lastIndexOf(\"/\");\n"
    "    return i < 0 ? \".\" : (i === 0 ? \"/\" : p.slice(0, i));\n"
    "  }\n"
    "  function isFile(p) {\n"
    "    try { return io.stat(p).kind === \"reg\"; } catch (e) { return false; }\n"
    "  }\n"
    "  function isDir(p) {\n"
    "    try { return io.stat(p).kind === \"dir\"; } catch (e) { return false; }\n"
    "  }\n"
    "  //  JAB-001: a bareword (no /, ./, ../) is NOT path-relative — it resolves\n"
    "  //  by scanning UP for `./jsrc ../jsrc …`, trying <jsrc>/<name> then\n"
    "  //  <name>.js in each.  Ceiling: $HOME/jsrc (under $HOME) else /jsrc.\n"
    "  //  GET-041: the jsrc-CLIMB runs ONCE — at the first lookup (startup) — and\n"
    "  //  its result is FROZEN as an array of absolute jsrc/ dir paths (symlinks\n"
    "  //  kept verbatim: a `$HOME/jsrc -> …` locator stays a locator).  Every bareword\n"
    "  //  then resolves against that fixed array, so a `jab get` re-scanning per\n"
    "  //  require can never wander into a tree it is mid-writing.  Explicit ./ ../\n"
    "  //  paths never touch the array — resolve() keeps them relative to the\n"
    "  //  requiring script's own dir.\n"
    "  function isExplicit(spec) {\n"
    "    return spec[0] === \"/\" || spec.slice(0, 2) === \"./\" ||\n"
    "           spec.slice(0, 3) === \"../\";\n"
    "  }\n"
    "  //  JAB-035: the FLOOR — the jsrc pack embedded in the binary (the global\n"
    "  //  `jsrcpack`, absent without -DJAB_JSRC), extracted once and appended LAST.\n"
    "  let packErr = null;\n"
    "  function packHex(b) {\n"
    "    let s = \"\";\n"
    "    for (let i = 8; i < 16; i++) s += (b[i] < 16 ? \"0\" : \"\") + b[i].toString(16);\n"
    "    return s;\n"
    "  }\n"
    "  function packStr(b, off, len) {\n"
    "    let end = off;\n"
    "    while (end < off + len && b[end] !== 0) end++;\n"
    "    return utf8.Decode(b.subarray(off, end));\n"
    "  }\n"
    "  //  Untar the inflated pack into `dir`: a 512-byte header per entry, then the\n"
    "  //  file bytes padded up to the next 512 boundary; a zero header ends it.\n"
    "  function packUntar(dir, raw) {\n"
    "    let off = 0;\n"
    "    while (off + 512 <= raw.length && raw[off] !== 0) {\n"
    "      let name = packStr(raw, off, 100);\n"
    "      const prefix = packStr(raw, off + 345, 155);\n"
    "      if (prefix) name = prefix + \"/\" + name;\n"
    "      const size = parseInt(packStr(raw, off + 124, 12).trim() || \"0\", 8);\n"
    "      const type = raw[off + 156];\n"
    "      off += 512;\n"
    "      if (type === 48 || type === 0) {          // '0' / NUL: a regular file\n"
    "        const p = dir + \"/\" + name;\n"
    "        io.mkdir(dirname(p));\n"
    "        const fd = io.open(p, \"c\");\n"
    "        try { io.writeAll(fd, raw.subarray(off, off + size)); }\n"
    "        finally { io.close(fd); }\n"
    "      }\n"
    "      off += (size + 511) & ~511;\n"
    "    }\n"
    "  }\n"
    "  //  Cache probe, then inflate+untar into a temp dir and rename it into place;\n"
    "  //  a lost race (the dir is already there) is a win — drop ours, use theirs.\n"
    "  function packExtract() {\n"
    "    const b = g.jsrcpack;\n"
    "    if (!b || b.length < 16 || b[0] !== 74 || b[1] !== 83 || b[2] !== 82)\n"
    "      return null;                              // no \"JSR\" pack: no floor\n"
    "    if (b[3] !== 1)\n"
    "      throw \"the built-in scripts are packed in a format this jab does not know\";\n"
    "    const home = io.getenv(\"HOME\");\n"
    "    const cache = io.getenv(\"XDG_CACHE_HOME\") || (home ? home + \"/.cache\" : \"\");\n"
    "    if (!cache)\n"
    "      throw \"neither XDG_CACHE_HOME nor HOME is set, so there is nowhere to \" +\n"
    "            \"unpack the built-in scripts\";\n"
    "    const dir = cache + \"/jsrcs/\" + packHex(b);\n"
    "    if (isDir(dir)) return dir;\n"
    "    const raw = new Uint8Array(b[4] + b[5] * 256 + b[6] * 65536 + b[7] * 16777216);\n"
    "    g.zip._inflate(b.subarray(16), raw, 0);     // the preamble pre-sizes it\n"
    "    const tmp = cache + \"/jsrcs/.tmp-\" + io.getpid();\n"
    "    io.mkdir(tmp);\n"
    "    try {\n"
    "      packUntar(tmp, raw);\n"
    "      io.rename(tmp, dir);\n"
    "    } catch (e) {\n"
    "      io.rmdir(tmp, true);\n"
    "      if (!isDir(dir)) throw e;\n"
    "    }\n"
    "    return dir;\n"
    "  }\n"
    "\n"
    "  let jsrcStack = null;                        // frozen once, at startup\n"
    "  function pinJsrcStack(start) {\n"
    "    const abs = normalize(start[0] === \"/\" ? start : io.cwd() + \"/\" + start);\n"
    "    const home = io.getenv(\"HOME\");\n"
    "    const ceil = home ? normalize(home) : \"/\";\n"
    "    let dir = abs;\n"
    "    const out = [];\n"
    "    while (true) {\n"
    "      const jsrc = dir + \"/jsrc\";\n"
    "      if (isDir(jsrc)) out.push(jsrc);\n"
    "      if (dir === ceil || dir === \"/\") break;\n"
    "      dir = dirname(dir);\n"
    "    }\n"
    "    //  JAB-035: the pack floor joins the one-time pin, BELOW every real jsrc.\n"
    "    try { const floor = packExtract(); if (floor) out.push(floor); }\n"
    "    catch (e) { packErr = e; }\n"
    "    jsrcStack = out;\n"
    "    return out;\n"
    "  }\n"
    "  function resolveJsrc(spec, from) {\n"
    "    const stack = jsrcStack || pinJsrcStack(from || io.cwd());\n"
    "    for (const jsrc of stack)\n"
    "      for (const c of [jsrc + \"/\" + spec, jsrc + \"/\" + spec + \".js\"])\n"
    "        if (isFile(c)) return c;\n"
    "    throw \"require: cannot find 'jsrc/\" + spec + \"' from '\" +\n"
    "          (from || io.cwd()) + \"'\" + (packErr ?\n"
    "          \" (jab could not unpack its built-in scripts: \" + packErr + \")\" : \"\");\n"
    "  }\n"
    "  function resolve(spec, baseDir) {\n"
    "    if (!isExplicit(spec)) return resolveJsrc(spec, baseDir);\n"
    "    let base = normalize(spec[0] === \"/\" ? spec : baseDir + \"/\" + spec);\n"
    "    for (const c of [base, base + \".js\", base + \"/index.js\"])\n"
    "      if (isFile(c)) return c;\n"
    "    throw \"require: cannot find '\" + spec + \"' from '\" + baseDir + \"'\";\n"
    "  }\n"
    "  //  JAB-010: memo (baseDir, spec) -> abs, consulted BEFORE resolve(), which\n"
    "  //  re-ran its io.stat ladder on every require — even a cache-hit one.\n"
    "  const resolved = new Map();\n"
    "  function resolveMemo(spec, baseDir) {\n"
    "    //  Skip a cwd-dependent pair (relative spec off a relative base): only\n"
    "    //  those can change under io.chdir, so today's semantics stay (JS-119).\n"
    "    if (isExplicit(spec) && spec[0] !== \"/\" && baseDir[0] !== \"/\")\n"
    "      return resolve(spec, baseDir);\n"
    "    const key = spec.length + \":\" + spec + baseDir;   // unambiguous\n"
    "    let abs = resolved.get(key);\n"
    "    if (abs === undefined) {\n"
    "      abs = resolve(spec, baseDir);            // throws: nothing memoized\n"
    "      resolved.set(key, abs);\n"
    "    }\n"
    "    return abs;\n"
    "  }\n"
    "  function makeRequire(baseDir) {\n"
    "    const req = (spec) => load(spec, baseDir);\n"
    "    req.resolve = (spec) => resolveMemo(spec, baseDir);\n"
    "    req.cache = cache;\n"
    "    return req;\n"
    "  }\n"
    "  function load(spec, baseDir) {\n"
    "    const abs = resolveMemo(spec, baseDir);\n"
    "    if (cache[abs]) return cache[abs].exports;\n"
    "    const src = utf8.Decode(io.mmap(abs, \"r\").data());\n"
    "    const module = { exports: {}, id: abs, filename: abs };\n"
    "    cache[abs] = module;                       // before eval: cycle-safe\n"
    "    const dir = dirname(abs);\n"
    "    //  JS-112: compile/eval failure evicts the cache entry and rethrows so a\n"
    "    //  retry re-evaluates (Node CommonJS); before-eval insert stays for cycles.\n"
    "    try {\n"
    "      const fn = new Function(\"module\", \"exports\", \"require\",\n"
    "                              \"__filename\", \"__dirname\", src);\n"
    "      fn(module, module.exports, makeRequire(dir), abs, dir);\n"
    "    } catch (e) { delete cache[abs]; throw e; }\n"
    "    return module.exports;\n"
    "  }\n"
    "\n"
    "  g.require = makeRequire(\".\");                 // top-level: resolve vs cwd\n"
    "\n"
    "  //  An EXPLICIT-path entry (`jab ./x.js`, `jab /abs/x.js`) runs via global\n"
    "  //  eval, so its top-level require would resolve `./lib/y.js` against the\n"
    "  //  CWD, not the script.  Rebind it to the script's OWN dir so a sibling\n"
    "  //  `require(\"./lib/y.js\")` works script-relative — no `here` idiom needed.\n"
    "  //  main.cpp calls this before eval'ing the file; bareword entries skip it\n"
    "  //  (they load through __main, which already binds require to the module dir).\n"
    "  g.__rebaseRequire = function (p) {\n"
    "    const abs = normalize(p[0] === \"/\" ? p : io.cwd() + \"/\" + p);\n"
    "    g.require = makeRequire(dirname(abs));\n"
    "  };\n"
    "\n"
    "  //  JAB: a bare/relative `.js` ENTRY (`jab foo.js`, `jab jsrc/main.js`) — NOT\n"
    "  //  an explicit path (main.cpp runs /,./,../ directly via global eval).  Resolve\n"
    "  //  it via the upward jsrc/-scan, pin it as argv[1], and load it as the program.\n"
    "  g.__runScript = function (spec) {\n"
    "    const abs = resolveJsrc(spec);\n"
    "    if (g.process && g.process.argv) g.process.argv[1] = abs;\n"
    "    return load(abs, dirname(abs));\n"
    "  };\n"
    "\n"
    "  //  JAB: the DEFAULT entry — any first arg that is NOT a `.js` file (a verb, a\n"
    "  //  `scheme:` URI, a non-.js path) and the no-arg `jab` route here (main.cpp\n"
    "  //  decides via the `.js` suffix and calls __main()).  Resolve jsrc/main.js by\n"
    "  //  the same upward jsrc/-scan, splice it in as argv[1] (so main.js's\n"
    "  //  process.argv[1] is its OWN jsrc/-root path — core/loop.js derives `_here`\n"
    "  //  from it — and the user's tokens stay at argv[2:] AS-IS, the cli contract:\n"
    "  //  verb=argv[2]), then run it; main.js (the resident loop) triages the rest.\n"
    "  g.__main = function () {\n"
    "    const abs = resolveJsrc(\"main.js\");\n"
    "    const av = g.process && g.process.argv;\n"
    "    if (av) g.process.argv = [av[0], abs].concat(av.slice(1));\n"
    "    return load(abs, dirname(abs));\n"
    "  };\n"
    "})(this);\n";

ok64 JABCInstallRequire(JSContext *ctx, JSValueConst global) {
    (void)ctx;
    (void)global;
    JABCExecute(JABC_REQUIRE_JS);
    return OK;
}
