//  JAB-036: jab/require.cpp — the synchronous CommonJS require(), a pure
//  embedded-JS bundle (GET-041 jsrc stack + JAB-035 pack floor), verbatim.
#include "JABC.h"

static const char *JABC_REQUIRE_JS =
    "(function (g) {\n"
    "  \"use strict\";\n"
    "  const io = g.io, utf8 = g.utf8;\n"
    "  const cache = {};\n"
    "\n"
    "  function normalize(p) {\n"
    "    const abs = p[0] === \"/\";\n"
    "    const out = [];\n"
    "    for (const s of p.split(\"/\")) {\n"
    "      if (s === \"\" || s === \".\") continue;\n"
    "      if (s === \"..\") {\n"
    "        if (out.length && out[out.length - 1] !== \"..\") out.pop();\n"
    "        else if (!abs) out.push(\"..\");\n"
    "      } else out.push(s);\n"
    "    }\n"
    "    return (abs ? \"/\" : \"\") + out.join(\"/\");\n"
    "  }\n"
    "  function dirname(p) {\n"
    "    const i = p.lastIndexOf(\"/\");\n"
    "    return i < 0 ? \".\" : (i === 0 ? \"/\" : p.slice(0, i));\n"
    "  }\n"
    "  function isFile(p) {\n"
    "    try { return io.stat(p).kind === \"reg\"; } catch (e) { return false; }\n"
    "  }\n"
    "  function isDir(p) {\n"
    "    try { return io.stat(p).kind === \"dir\"; } catch (e) { return false; }\n"
    "  }\n"
    "  //  QJAB-002: a bareword (no /, ./, ../) is NOT path-relative — it resolves\n"
    "  //  against THE require base, ONE per process, picked by the three exclusive\n"
    "  //  modes below: <base>/<name> then <base>/<name>.js, and nowhere else.\n"
    "  //  Explicit ./ ../ / paths never touch the base — resolve() keeps them\n"
    "  //  relative to the requiring module's own dir (CommonJS).\n"
    "  function isExplicit(spec) {\n"
    "    return spec[0] === \"/\" || spec.slice(0, 2) === \"./\" ||\n"
    "           spec.slice(0, 3) === \"../\";\n"
    "  }\n"
    "  //  JAB-035: the jsrc pack embedded in the binary (the global `jsrcpack`,\n"
    "  //  absent without -DJAB_JSRC), extracted once into the user's cache.\n"
    "  function packHex(b) {\n"
    "    let s = \"\";\n"
    "    for (let i = 8; i < 16; i++) s += (b[i] < 16 ? \"0\" : \"\") + b[i].toString(16);\n"
    "    return s;\n"
    "  }\n"
    "  function packStr(b, off, len) {\n"
    "    let end = off;\n"
    "    while (end < off + len && b[end] !== 0) end++;\n"
    "    return utf8.Decode(b.subarray(off, end));\n"
    "  }\n"
    "  //  Untar the inflated pack into `dir`: a 512-byte header per entry, then the\n"
    "  //  file bytes padded up to the next 512 boundary; a zero header ends it.\n"
    "  function packUntar(dir, raw) {\n"
    "    let off = 0;\n"
    "    while (off + 512 <= raw.length && raw[off] !== 0) {\n"
    "      let name = packStr(raw, off, 100);\n"
    "      const prefix = packStr(raw, off + 345, 155);\n"
    "      if (prefix) name = prefix + \"/\" + name;\n"
    "      const size = parseInt(packStr(raw, off + 124, 12).trim() || \"0\", 8);\n"
    "      const type = raw[off + 156];\n"
    "      off += 512;\n"
    "      if (type === 48 || type === 0) {          // '0' / NUL: a regular file\n"
    "        const p = dir + \"/\" + name;\n"
    "        io.mkdir(dirname(p));\n"
    "        const fd = io.open(p, \"c\");\n"
    "        try { io.writeAll(fd, raw.subarray(off, off + size)); }\n"
    "        finally { io.close(fd); }\n"
    "      }\n"
    "      off += (size + 511) & ~511;\n"
    "    }\n"
    "  }\n"
    "  //  Cache probe, then inflate+untar into a temp dir and rename it into place;\n"
    "  //  a lost race (the dir is already there) is a win — drop ours, use theirs.\n"
    "  function packExtract() {\n"
    "    const b = g.jsrcpack;\n"
    "    if (!b || b.length < 16 || b[0] !== 74 || b[1] !== 83 || b[2] !== 82)\n"
    "      return null;                              // no \"JSR\" pack: no floor\n"
    "    if (b[3] !== 1)\n"
    "      throw \"the built-in scripts are packed in a format this jab does not know\";\n"
    "    const home = io.getenv(\"HOME\");\n"
    "    const cache = io.getenv(\"XDG_CACHE_HOME\") || (home ? home + \"/.cache\" : \"\");\n"
    "    if (!cache)\n"
    "      throw \"neither XDG_CACHE_HOME nor HOME is set, so there is nowhere to \" +\n"
    "            \"unpack the built-in scripts\";\n"
    "    const dir = cache + \"/jsrcs/\" + packHex(b);\n"
    "    if (isDir(dir)) return dir;\n"
    "    const raw = new Uint8Array(b[4] + b[5] * 256 + b[6] * 65536 + b[7] * 16777216);\n"
    "    g.zip._inflate(b.subarray(16), raw, 0);     // the preamble pre-sizes it\n"
    "    const tmp = cache + \"/jsrcs/.tmp-\" + io.getpid();\n"
    "    io.mkdir(tmp);\n"
    "    try {\n"
    "      packUntar(tmp, raw);\n"
    "      io.rename(tmp, dir);\n"
    "    } catch (e) {\n"
    "      io.rmdir(tmp, true);\n"
    "      if (!isDir(dir)) throw e;\n"
    "    }\n"
    "    return dir;\n"
    "  }\n"
    "\n"
    "  //  Mode 3's climb: the FIRST jsrc/ at or above the cwd, and no further —\n"
    "  //  a higher jsrc/ is invisible.  Ceiling: $HOME (under $HOME) else /.\n"
    "  function climbJsrc() {\n"
    "    const home = io.getenv(\"HOME\");\n"
    "    const ceil = home ? normalize(home) : \"/\";\n"
    "    let dir = normalize(io.cwd());\n"
    "    while (true) {\n"
    "      const jsrc = dir + \"/jsrc\";\n"
    "      if (isDir(jsrc)) return jsrc;\n"
    "      if (dir === ceil || dir === \"/\") return null;\n"
    "      dir = dirname(dir);\n"
    "    }\n"
    "  }\n"
    "  //  QJAB-002: the ONE require base, frozen at the first bareword.  Three\n"
    "  //  EXCLUSIVE modes in order: 1. the built-in bundle (a packed build is\n"
    "  //  bundle-ONLY, no climb at all); 2. the entry script's own dir; 3. the\n"
    "  //  first jsrc/ above the cwd.  There is no second source in any mode.\n"
    "  let requireBase = null;\n"
    "  let scriptDir = null;                        // mode 2, set by __pinScript\n"
    "  function pinBase(spec) {\n"
    "    if (requireBase !== null) return requireBase;\n"
    "    requireBase = packExtract() || scriptDir || climbJsrc();\n"
    "    if (requireBase === null)\n"
    "      throw \"require: cannot find 'jsrc/\" + spec + \"': there is no jsrc/ \" +\n"
    "            \"directory at or above '\" + io.cwd() + \"'\";\n"
    "    return requireBase;\n"
    "  }\n"
    "  function resolveJsrc(spec) {\n"
    "    const base = pinBase(spec);\n"
    "    for (const c of [base + \"/\" + spec, base + \"/\" + spec + \".js\"])\n"
    "      if (isFile(c)) return c;\n"
    "    throw \"require: cannot find '\" + spec + \"' in '\" + base + \"'\";\n"
    "  }\n"
    "  function resolve(spec, baseDir) {\n"
    "    if (!isExplicit(spec)) return resolveJsrc(spec);\n"
    "    let base = normalize(spec[0] === \"/\" ? spec : baseDir + \"/\" + spec);\n"
    "    for (const c of [base, base + \".js\", base + \"/index.js\"])\n"
    "      if (isFile(c)) return c;\n"
    "    throw \"require: cannot find '\" + spec + \"' from '\" + baseDir + \"'\";\n"
    "  }\n"
    "  //  JAB-010: memo (baseDir, spec) -> abs, consulted BEFORE resolve(), which\n"
    "  //  re-ran its io.stat ladder on every require — even a cache-hit one.\n"
    "  const resolved = new Map();\n"
    "  function resolveMemo(spec, baseDir) {\n"
    "    //  Skip a cwd-dependent pair (relative spec off a relative base): only\n"
    "    //  those can change under io.chdir, so today's semantics stay (JS-119).\n"
    "    if (isExplicit(spec) && spec[0] !== \"/\" && baseDir[0] !== \"/\")\n"
    "      return resolve(spec, baseDir);\n"
    "    const key = spec.length + \":\" + spec + baseDir;   // unambiguous\n"
    "    let abs = resolved.get(key);\n"
    "    if (abs === undefined) {\n"
    "      abs = resolve(spec, baseDir);            // throws: nothing memoized\n"
    "      resolved.set(key, abs);\n"
    "    }\n"
    "    return abs;\n"
    "  }\n"
    "  function makeRequire(baseDir) {\n"
    "    const req = (spec) => load(spec, baseDir);\n"
    "    req.resolve = (spec) => resolveMemo(spec, baseDir);\n"
    "    req.cache = cache;\n"
    "    return req;\n"
    "  }\n"
    "  function load(spec, baseDir) {\n"
    "    const abs = resolveMemo(spec, baseDir);\n"
    "    if (cache[abs]) return cache[abs].exports;\n"
    "    const src = utf8.Decode(io.mmap(abs, \"r\").data());\n"
    "    const module = { exports: {}, id: abs, filename: abs };\n"
    "    cache[abs] = module;                       // before eval: cycle-safe\n"
    "    const dir = dirname(abs);\n"
    "    //  JS-112: compile/eval failure evicts the cache entry and rethrows so a\n"
    "    //  retry re-evaluates (Node CommonJS); before-eval insert stays for cycles.\n"
    "    try {\n"
    "      const fn = new Function(\"module\", \"exports\", \"require\",\n"
    "                              \"__filename\", \"__dirname\", src);\n"
    "      fn(module, module.exports, makeRequire(dir), abs, dir);\n"
    "    } catch (e) { delete cache[abs]; throw e; }\n"
    "    return module.exports;\n"
    "  }\n"
    "\n"
    "  g.require = makeRequire(\".\");                 // top-level: resolve vs cwd\n"
    "\n"
    "  //  QJAB-002 mode 2: a `.js` ENTRY (`jab x.js`, `jab ./x.js`, `jab /abs/x.js`)\n"
    "  //  is a file path off the cwd, run via global eval, and ITS OWN DIR is the\n"
    "  //  require base — `require(\"lib/y.js\")` and `require(\"./lib/y.js\")` alike\n"
    "  //  join it, and no jsrc/ is ever consulted.  main.c calls this before eval.\n"
    "  g.__pinScript = function (p) {\n"
    "    const abs = normalize(p[0] === \"/\" ? p : io.cwd() + \"/\" + p);\n"
    "    scriptDir = dirname(abs);\n"
    "    g.require = makeRequire(scriptDir);\n"
    "  };\n"
    "\n"
    "  //  JAB: the DEFAULT entry — any first arg that is NOT a `.js` file (a verb, a\n"
    "  //  `scheme:` URI, a non-.js path) and the no-arg `jab` route here (main.c\n"
    "  //  decides via the `.js` suffix and calls __main()).  QJAB-002: main.js comes\n"
    "  //  from THE base (mode 1 bundle or mode 3 climb), spliced in as argv[1] (so\n"
    "  //  process.argv[1] is its OWN jsrc/-root path — core/loop.js derives `_here`\n"
    "  //  from it — and the user's tokens stay at argv[2:] AS-IS, the cli contract:\n"
    "  //  verb=argv[2]), then run it; main.js (the resident loop) triages the rest.\n"
    "  g.__main = function () {\n"
    "    const abs = resolveJsrc(\"main.js\");\n"
    "    const av = g.process && g.process.argv;\n"
    "    if (av) g.process.argv = [av[0], abs].concat(av.slice(1));\n"
    "    return load(abs, dirname(abs));\n"
    "  };\n"
    "})(this);\n";

ok64 JABCInstallRequire(JSContext *ctx, JSValueConst global) {
    (void)ctx;
    (void)global;
    JABCExecute(JABC_REQUIRE_JS);
    return OK;
}
